/**
 * AI Fishing Report — displays the daily natural-language fishing forecast
 * generated by Claude. Shows regional reports with conditions summary.
 */

import { useState, useEffect } from 'react'
import { cn } from '../../lib/utils'

const TILE_BASE = import.meta.env.VITE_HRRR_TILE_URL || 'https://xhac6pdww5.execute-api.us-east-2.amazonaws.com'

interface RegionReport {
  region: string
  description: string
  text: string
  conditions?: Record<string, any>
  generatedAt: string
  error?: string
}

interface ReportManifest {
  date: string
  generatedAt: string
  regions: string[]
  reports: Record<string, RegionReport>
}

const REGION_ICONS: Record<string, string> = {
  'se-atlantic': '🌴',
  'gulf': '🛢️',
  'ne-atlantic': '🦞',
  'pacific': '🌊',
}

function degreesToCardinal(deg: number): string {
  const dirs = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW']
  return dirs[Math.round(deg / 22.5) % 16]
}

export default function FishingReport() {
  const [manifest, setManifest] = useState<ReportManifest | null>(null)
  const [loading, setLoading] = useState(true)
  const [activeRegion, setActiveRegion] = useState('')
  const [error, setError] = useState('')

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch(`${TILE_BASE}/tiles/hrrr/fishing-reports/latest.json`).catch(() => null)
        if (!res || !res.ok) throw new Error('No report available')
        const data = await res.json()
        setManifest(data)
        if (data.regions?.length) setActiveRegion(data.regions[0])
      } catch (e: any) {
        setError(e.message)
      }
      setLoading(false)
    }
    load()
  }, [])

  if (loading) {
    return (
      <div className="p-6 text-center">
        <div className="w-5 h-5 border-2 border-cyan-500/30 border-t-cyan-500 rounded-full animate-spin mx-auto" />
        <p className="text-xs text-slate-500 mt-3">Loading fishing report...</p>
      </div>
    )
  }

  if (error || !manifest) {
    return (
      <div className="p-6 text-center">
        <p className="text-sm text-slate-500">No fishing report available yet.</p>
        <p className="text-xs text-slate-600 mt-1">Reports are generated daily at 6:00 AM ET.</p>
      </div>
    )
  }

  const report = manifest.reports[activeRegion]
  const cond = report?.conditions

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2">
            <svg className="w-4 h-4 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            AI Fishing Report
          </h3>
          <p className="text-[10px] text-slate-600 mt-0.5">
            Generated {new Date(manifest.generatedAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
          </p>
        </div>
        <span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400">
          Powered by Claude AI
        </span>
      </div>

      {/* Region pills */}
      <div className="flex gap-1.5 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        {manifest.regions.map((id) => {
          const r = manifest.reports[id]
          return (
            <button
              key={id}
              onClick={() => setActiveRegion(id)}
              className={cn(
                'flex-shrink-0 text-xs px-3 py-1.5 rounded-full border transition-all whitespace-nowrap',
                activeRegion === id
                  ? 'bg-cyan-500/20 border-cyan-500/50 text-cyan-300'
                  : 'bg-ocean-800 border-ocean-600 text-slate-500 hover:text-slate-300',
              )}
            >
              {REGION_ICONS[id] || '🗺️'} {r?.region || id}
            </button>
          )
        })}
      </div>

      {/* Conditions summary */}
      {report && cond && (
        <div className="grid grid-cols-3 gap-1.5">
          {cond.sst != null && (
            <div className="bg-ocean-800 rounded-lg px-2 py-1.5 text-center">
              <div className="text-[9px] text-slate-500 uppercase">SST</div>
              <div className="text-xs font-bold text-cyan-300 font-mono">{Math.round(cond.sst)}°F</div>
            </div>
          )}
          {cond.windSpeed != null && (
            <div className="bg-ocean-800 rounded-lg px-2 py-1.5 text-center">
              <div className="text-[9px] text-slate-500 uppercase">Wind</div>
              <div className="text-xs font-bold text-slate-200 font-mono">{cond.windSpeed} mph {degreesToCardinal(cond.windDirection || 0)}</div>
            </div>
          )}
          {cond.waveHeight != null && (
            <div className="bg-ocean-800 rounded-lg px-2 py-1.5 text-center">
              <div className="text-[9px] text-slate-500 uppercase">Seas</div>
              <div className="text-xs font-bold text-slate-200 font-mono">{cond.waveHeight} ft</div>
            </div>
          )}
          {cond.pressure != null && (
            <div className="bg-ocean-800 rounded-lg px-2 py-1.5 text-center">
              <div className="text-[9px] text-slate-500 uppercase">Pressure</div>
              <div className="text-xs font-bold text-slate-200 font-mono">{cond.pressure.toFixed(0)} mb</div>
            </div>
          )}
          {cond.moonPhase && (
            <div className="bg-ocean-800 rounded-lg px-2 py-1.5 text-center">
              <div className="text-[9px] text-slate-500 uppercase">Moon</div>
              <div className="text-xs font-bold text-slate-200">{cond.moonPhase}</div>
            </div>
          )}
          {cond.cloudCover != null && (
            <div className="bg-ocean-800 rounded-lg px-2 py-1.5 text-center">
              <div className="text-[9px] text-slate-500 uppercase">Clouds</div>
              <div className="text-xs font-bold text-slate-200 font-mono">{cond.cloudCover}%</div>
            </div>
          )}
        </div>
      )}

      {/* Report text */}
      {report && (
        <div className="bg-ocean-800/50 border border-ocean-700/50 rounded-xl p-4">
          <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-line">{report.text}</p>
        </div>
      )}
    </div>
  )
}
